Django/day04/mydb/mydb/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^testdb/',include('testdb.urls'))
]

Django/day04/mydb/testdb/urls.py
# !/usr/bin/env python
# coding=utf-8

from django.conf.urls import url
from . import views
# 对不同app的url配置添加命名空间
app_name = 'testdb'
urlpatterns = [
	url(r'^test$',views.test,name='test'),
	url(r'^data$',views.data,name='data'),
	url(r'^data/get$',views.get_data,name='get_data'),
	url(r'^test/base$',views.test_base,name='test_base'),
	url(r'^router/.+$',views.test2,name='test2'),
	url(r'^router$',views.router,name='router'),
]

Django/day04/mydb/testdb/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Person(models.Model):
	first_name = models.CharField(max_length = 30)
	last_name = models.CharField(max_length = 30)

class Persons(models.Model):
    SHIRT_SIZES = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
    )
    name = models.CharField(max_length=60)
    shirt_size = models.CharField(max_length=1, choices=SHIRT_SIZES)

class Fruit(models.Model):
	name = models.CharField(max_length=100,primary_key=True)
	price = models.DecimalField(max_digits=20,decimal_places=2)

# 多对一的关系
class Reporter(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	email = models.EmailField()

	def __unicode__(self):
		return "%s %s" %(self.first_name,self.last_name)

class Article(models.Model):
	headline = models.CharField(max_length=30)
	pub_date = models.DateField()
	reporter = models.ForeignKey(Reporter,on_delete=models.CASCADE)

	def __unicode__(self):
		return self.headline

	class Meta:
		ordering = ('headline',)

# 多对多的关系
class Publication(models.Model):
	title = models.CharField(max_length=100)

	def __unicode__(self):
		return self.title

	class Meta:
		ordering = ('title',)

class Articles(models.Model):
	headline = models.CharField(max_length=100)
	publications = models.ManyToManyField(Publication)

	def __unicode__(self):
		return self.headline

	class Meta:
		ordering = ('headline',)

# 自定义多对多的关系
class Group(models.Model):
	name = models.CharField(max_length=128)
	members = models.ManyToManyField(Person,through='Membership')

	def __unicode__(self):
		return self.name

class Membership(models.Model):
	person = models.ForeignKey(Person,on_delete=models.CASCADE)
	group = models.ForeignKey(Group,on_delete=models.CASCADE)
	date_joined = models.DateField()
	invite_reason = models.CharField(max_length=64)

# 一对一的关系
class Place(models.Model):
	name = models.CharField(max_length=50)
	address = models.CharField(max_length=80)
	def __unicode__(self):
		return "%s the place" % self.name

class Restaurant(models.Model):
	place = models.OneToOneField(Place,on_delete=models.CASCADE,primary_key=True)
	serves_hot_dogs = models.BooleanField(default=False)
	serves_pizza_dogs = models.BooleanField(default=False)

	def __unicode__(self):
		return "%s the restaurant" % self.place.name

class Waiter(models.Model):
	restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE)
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return "%s the waiter at %s" % (self.name,self.restaurant)

Django/day04/mydb/testdb/views.py
# coding=utf-8
from django.shortcuts import render
from django.views.decorators.http import require_http_methods,require_GET,require_POST
from django.http import HttpResponse,JsonResponse
from django.template import loader
from datetime import datetime

from .models import Reporter,Article

# Create your views here.


@require_http_methods(["GET","POST"])
def test(request):
	return render(request,'testdb/test.html',context={"data":'this is get test html...'})

@require_GET
def data(request):
	# select_template与get_template效果类似，都会返回一个Template对象，只是接受的第一个参数不一样
	# 前者使用List列表接受多个template，template engine 查找template直到存在为止就不会继续查找
	template = loader.select_template(['testdb/data_test.html','testdb/datas.html','testdb/data2.html','testdb/data.html'])
	context = {
		"data2":"this is select_template...",
		"data":"this is get test html...",
		"data_test":"this is data_test html...",
		"my_date":datetime.now(),
		"list":[1,2,3],
		"filesize":123223234,
		"athlete_list":[
			{
				'name':'Micale Jordan',
				'age':60,
				'job':'basketball'
			},
			{
				'name':'LiLi',
				'age':30,
				'job':'volleball'
			},
			{
				'name':'Norda ell',
				'age':30,
				'job':'tennis'
			}
		],
	}
	return HttpResponse(template.render(context,request))
	# return render(request,'testdb/data.html',context={"data":'this is get test html...'})

@require_POST
def post_data(request):
	return HttpResponse('this is post request data...')

@require_GET
def get_data(request):
	return HttpResponse('this is get request data...')

@require_GET
def test_base(request):
	r = Reporter.objects.get(pk=1)
	data = {
		"name":"youyou",
		"not_name":"<script>alert('hello')</script>",
		"not_name2":"<b>粗体</b>",
		"r1":r
	}
	return render(request,'testdb/test_base.html',context=data)

@require_GET
def test2(request):
	return render(request,'testdb/test2.html')

@require_GET
def router(request):
	return render(request,'testdb/router.html')

Django/day04/mydb/templates/testdb/data_test.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	dirs---{{data_test}}
	{# this is comments #}
	<br>
	{{data_test|title}}
	{# title过滤器可以使得英文首字母大写 #}
	<br>
	{% for x in list %}
		{% cycle 'odd_num' 'even_num' %}
		{{x}}
		{% cycle 'odd' 'even' %}
		<br>
	{% endfor%}
	<br>
	<h2>内置的常用过滤器：</h2>
	date：{{my_date}}===>{{ my_date|date:"Y-m-d" }}===>{{ my_date|date:'D d M Y'}}===>{{my_date|date:"SHORT_DATE_FORMAT"}}===>{{my_date|date:"SHORT_DATETIME_FORMAT"}}===>{{my_date|date:"DATE_FORMAT"}}===>{{my_date|date:"DATETIME_FORMAT"}}<br>
	default：{{nothing|default:'nothing...'}}<br>
	length：{{value|length}}----{{list|length}}<br>
	filesizeformat：{{filesize|filesizeformat}}<br>
	add：{{filesize}}===>{{filesize|add:2}}-----{{filesize}}===>{{filesize|add:'3'}}-----{{list|add:list}}<br>
	capfirst：{{data2|capfirst}}<br>
	cut：{{"String with spaces"|cut:" "}}<br>
	<h2>内置的常用指令标签：</h2>
	for：<br>
	<ul>
		{% for athlete in athlete_list %}
			<li>{{athlete.name}}---{{athlete.age}}---{{athlete.job}}</li>
		{% endfor %}
	</ul>
	if,elif,and else <br>
	{% if athlete_list %}
		Number of athletes: {{ athlete_list|length }}
	{% elif athlete_in_locker_room_list %}
		Athletes should be out the locker room soon!
	{% else %}
		No athletes
	{% endif %}<br>
	{% if athlete_lists|length > 3 %}
		{% for athlete in athlete_list %}
			<p>{{athlete.name}}---{{athlete.age}}---{{athlete.job}}</p>
		{% endfor %}
	{% else %}
		 Athlete: {{ athlete_list.0.name }}---{{ athlete_list.1.name }}---{{ athlete_list.2.name }}---{{ athlete_list.3.name }}---
	{% endif %}

	<h2>模板的注解：</h2>
	{# {% if athlete_lists|length > 3 %}
			{% for athlete in athlete_list %}
				<p>{{athlete.name}}---{{athlete.age}}---{{athlete.job}}</p>
			{% endfor %}
		{% else %}
			 Athlete: {{ athlete_list.0.name }}---{{ athlete_list.1.name }}---{{ athlete_list.2.name }}---{{ athlete_list.3.name }}---
		{% endif %} #}<br>
	{# title过滤器可以 {# 。。。 #} 使得英文首字母大写 #}
	{% comment %}
		这是多行注释
		这是多行注释
		这是多行注释
		这是多行注释
		只能在后端开发人员看到

		{% if athlete_lists|length > 3 %}
			{% for athlete in athlete_list %}
				<p>{{athlete.name}}---{{athlete.age}}---{{athlete.job}}</p>
			{% endfor %}
		{% else %}
			 Athlete: {{ athlete_list.0.name }}---{{ athlete_list.1.name }}---{{ athlete_list.2.name }}---{{ athlete_list.3.name }}---
		{% endif %}
	{% endcomment %}
	{% comment %}
		多行注释不能内嵌
	{% endcomment %}
</body>
</html>

Django/day04/mydb/templates/testdb/router.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>router</title>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
        }
        div.router-wrap {
            width: 100%;
            height: 100%;
            background: #fefefe;
        }
        a {
            padding: 10px;  
            color: pink;
            font-size: 25px;
            font-weight: bold;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="router-wrap">
        <a href="#/black">黑色</a><br>
        <a href="#/green">绿色</a><br>
        <a href="#/red">红色</a>
    </div>
    <script>
        // 创建Router构造函数
        // currentHash为当前hash值，routes为路径对象
        function Router() {
            this.currentHash = '/';
            this.routes = {};
            this.init();
        }

        // 注册路径，每个路径对应一个回调函数。 
        Router.prototype.route = function (path, callback) {
            this.routes[path] = callback || function () {
                alert('未定义回调函数！');
            }
        }

        // 更新页面函数
        Router.prototype.refresh = function () {
            this.currentHash = location.hash.slice(1) || '/';
            this.routes[this.currentHash]();
        }

        // 初始化
        Router.prototype.init = function () {
            var self = this;
            window.addEventListener('load', function () {
                console.log("触发了load...");
                self.refresh();
            }, false);  

            window.addEventListener('hashchange', function () {
            	console.log("触发了hashchange...");
                self.refresh();
            });
        }
    </script>

    <script>
        // window.addEventListener("load",function(){
            var wrap = document.querySelector('.router-wrap');
            // 不能将Router对象的初始化放在页面初始化完毕的代码内部，如window.onload...，$(function(){})...
            // 否则在页面初始化后，初始路由无法对应匹配执行的BUG
	        window.Router = new Router();

	        Router.route('/', function () {
	            wrap.style.backgroundColor = '#fefefe';
	        });

	        Router.route('/black', function () {
	            wrap.style.backgroundColor = 'black';
	        });

	        Router.route('/green', function () {
	            wrap.style.backgroundColor = 'green';
	        });

	        Router.route('/red', function () {
	            wrap.style.backgroundColor = 'red';
	        });

	        window.onpopstate = function(){
	        	console.log("触发了popstate...");
	        }
    	// });
    </script>
</body>
</html>

Django/day04/mydb/templates/testdb/test2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>router</title>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
        }
        div.router-wrap {
            width: 100%;
            height: 100%;
            background: #efefef;
        }
        a {
            display: inline-block;
            padding: 10px;  
            color: pink;
            font-size: 25px;
            font-weight: bold;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="router-wrap">
        <a href="/testdb/router/black" class="history-link">黑色</a><br>
        <a href="/testdb/router/green" class="history-link">绿色</a><br>
        <a href="/testdb/router/red" class="history-link">红色</a>
    </div>

    <script>
        // 创建Router构造函数
        function Router() {
            this.currentRoute = '';
            this.routes = {};
            this.init();
        }

        // 注册路由函数
        Router.prototype.route = function (path, callback) {

            // 根据type类型，选择相应的history api。  
            this.routes[path] = function (type) {
                if (type == 1) {
                    history.pushState({path: path}, '', path);
                } else if (type == 2) {
                    history.replaceState({path: path}, '', path);
                }
                callback();
            }
        }

        // 更新页面
        Router.prototype.refresh = function (path, type) {
            this.routes[path](type);
        }

        // 初始化
        Router.prototype.init = function () {

            var self = this;

            // 重新加载函数，这里使用的主机是http://localhost:8088/
            window.addEventListener('load', function () {
                console.log("执行了load...");
                self.currentRoute = location.href.slice(location.href.indexOf('/', 8));
                console.log(self.currentRoute);
                self.refresh(self.currentRoute);
            });

            // 当用户点击前进后退按钮时触发函数
            window.addEventListener('popstate', function () {
                console.log('history.state.path:', history.state.path);
                self.currentRoute = history.state.path;
                self.refresh(self.currentRoute, 2);
            }, false);

            // 对所有的link标签进行绑定事件
            var historyLinks = document.querySelectorAll('.history-link');
            for (var i = 0, len = historyLinks.length; i < len; i++) {
                historyLinks[i].onclick = function(e) {
                    // 阻止默认
                    e.preventDefault();
                    self.currentRoute = e.target.getAttribute('href');
                    self.refresh(self.currentRoute, 1);
                }
            }
        }
    </script>

    <script>
        // window.addEventListener("load",function(){
            var wrap = document.querySelector('.router-wrap');
            // 不能将Router对象的初始化放在页面初始化完毕的代码内部，如window.onload...，$(function(){})...
            // 否则在页面初始化后，初始路由无法对应匹配执行
            // 实例化Router
            window.Router = new Router();


            // 注册路由，实现相应功能
                
            Router.route('/testdb/router/test2', function () {
                wrap.style.backgroundColor = '#efefef'
            });

            Router.route('/testdb/router/black', function () {
                wrap.style.backgroundColor = 'black';
            });

            Router.route('/testdb/router/green', function () {
                wrap.style.backgroundColor = 'green';
            });

            Router.route('/testdb/router/red', function () {
                wrap.style.backgroundColor = 'red';
            });
        // },false);
    </script>
</body>
</html>

Django/day04/mydb/testdb/templates/testdb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} base html{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'testdb/style.css'%}">
</head>
<body>
	<div id=sidebar>
		{% block sidebar%}
			<ul>
				<li><a href="/">Home</a></li>
				<li><a href="/blog">Blog</a></li>
			</ul>
		{% endblock %}
	</div>
	{% autoescape off %}
		<div id="content">
			{% block content %}
				base.....html
			{% endblock %}
		</div>
	{% endautoescape %}
</body>
</html>

Django/day04/mydb/testdb/templates/testdb/base_foot.html
{% extends 'testdb/base.html' %}
<div id="foot">
	这是底部
</div>

Django/day04/mydb/testdb/templates/testdb/base_header.html
{% extends 'testdb/base.html' %}
<div id="header">
	这是头部...
</div>

Django/day04/mydb/testdb/templates/testdb/data.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	{{data}}
</body>
</html>

Django/day04/mydb/testdb/templates/testdb/data2.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	{{data2}}
</body>
</html>

Django/day04/mydb/testdb/templates/testdb/data_test.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	app---{{data_test}}
</body>
</html>

Django/day04/mydb/testdb/templates/testdb/test.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>测试</title>
</head>
<body>
	{{data}}
</body>
</html>

Django/day04/mydb/testdb/templates/testdb/test_base.html
{% extends "testdb/base.html" %}

{% load humanize %}
{% block title %} My test_base {% endblock %}
{% block sidebar %}
	{{block.super}}
	<p>这是继承了父类内容，额外增加的内容</p>
{% endblock sidebar %}

{% block content %}
	this is test_base。。。html <br>	
	hello {{name}}
	hello {{not_name2}}
	hello {{not_name}}
	{% autoescape on %}
		<h2>hello {{not_name}}</h2>
		{{data|default:'<script type="text/javascript">alert(1)</script>'}}
		<br>
		{{r1.first_name}} {{r1.last_name}}发布了{{r1.article_set.count}}篇文章
		{% for a in r1.article_set.all %}
			----<a href="javascript:void(0);">{{a.headline}}{{a.pub_date}}</a>
		{% endfor %}
		<br>
		加载第三方标签或者过滤器库----{{ 45000|intcomma }}
	{% endautoescape %}
{% endblock %}