Django/day02/mysite/account/urls.py
# !/usr/bin/env python
# coding=utf-8

from django.conf.urls import url
from . import views

app_name = 'account'
urlpatterns = [
	url(r'^$',views.test,name='test'),
	url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
]

Django/day02/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls), 
    url(r'^polls/', include('polls.urls')),
    url(r'^account/', include('account.urls')),
]

Django/day02/mysite/polls/urls.py
# !/usr/bin/env python
# coding=utf-8

from django.conf.urls import url
from . import views
# 对不同app的url配置添加命名空间
app_name = 'polls'
urlpatterns = [
	# url(r'^$',views.index,name='index'),
	# url(r'^test$',views.test,name='test'),
	# url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
	# url(r'^specifics/(?P<question_id>[0-9]+)/$',views.detail,name='detail2'),
	# url(r'^(?P<question_id>[0-9]+)/results/$',views.results,name='results'),
	# url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
	# url(r'^latest\.html|polls/latest\.html$',views.latest,name='latest'),
	# url(r'^test2\.html$',views.test2,name='test2'),
	url(r'^$',views.IndexView.as_view(),name='index'),
	url(r'^test$',views.test,name='test'),
	url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
	url(r'^specifics/(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail2'),
	url(r'^(?P<pk>[0-9]+)/results/$',views.ResultsView.as_view(),name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
	url(r'^latest\.html|polls/latest\.html$',views.latest,name='latest'),
	url(r'^test2\.html$',views.test2,name='test2'),
]

Django/day02/mysite/account/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Django/day02/mysite/polls/models.py
# coding=utf-8
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')


	# 不支持中文
	# def __str__(self):
	# 	return self.question_text
	# 支持中文
	def __unicode__(self):
		return self.question_text
	def was_published_recently(self):
		# return self.pub_date >= timezone.now()-datetime.timedelta(days=1)
		return timezone.now()-datetime.timedelta(days=1) <= self.pub_date <= timezone.now()

	# 通过以下几个属性对 对象的方法进行属性的升降序设置，按照发布日期排序
	was_published_recently.admin_order_field = 'pub_date'
	# 控制显示图标还是文字
	was_published_recently.boolean = True
	# 表头的标题
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question,on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice_text
class Test(models.Model):
	name = models.CharField(max_length=100)
	text = models.CharField(max_length=200)
	
	def __unicode__(self):
		return self.name

Django/day02/mysite/account/views.py
from django.shortcuts import render

# Create your views here.

def test(request):
	data = {
		'name':"account is page"
	}
	return render(request,'account/index.html',context=data)

def detail(request,question_id):
	return render(request,'account/detail.html',context={"message":'this is a detail page...',"question_id":question_id})

Django/day02/mysite/polls/views.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-

from django.shortcuts import render,get_object_or_404,get_list_or_404

# Create your views here.

from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from .models import Question,Choice

def index(request):
	# return HttpResponse("Hello, world. You're at the polls index.")
	# 按照发布日期（pub_date）降序（-）查询前五的问题条目
	# latest_question_list = Question.objects.order_by('-pub_date')[:5]
	latest_question_list = Question.objects.order_by('-pub_date')
	# output = ','.join([q.question_text for q in latest_question_list])
	# return HttpResponse(output)
	# 获取视图模板对象，默认是去templates文件夹中查找
	template = loader.get_template('polls/index.html')
	# 定义上下文环境的数据源
	context = {
		'latest_question_list':latest_question_list,
		'message':'这是一个主页的数据源'
	}

	# 返回视图和数据给客户端
	# return HttpResponse(template.render(context,request))
	# 可以使用以下代码替代上面的返回
	return render(request,'polls/index.html',context=context)

class IndexView(generic.ListView):
	# 默认template_name 是应用名/模型名_文件名,需要改变则要进行重写
	template_name = 'polls/index.html'
	# 默认是question_list，改变上下文环境数据中的数据List字段
	context_object_name = 'latest_question_list'

	# 必须重写查询方法
	def get_queryset(self):
		# return Question.objects.order_by('-pub_date')[:5]
		# return Question.objects.order_by('-pub_date')
		# 查询发布日期小于或者等于当前日期的数据
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

	# 需要携带更多其他参数，如下进行设置
	def get_context_data(self,**kwargs):
		context = super(IndexView,self).get_context_data(**kwargs)
		context['now'] = timezone.now()	
		context['message'] = '这是一个主页的数据源'
		# print context
		return context	

def test(request):
	# return HttpResponse("Hello, world. You're at the polls test.",content_type='text/plain')
	response = HttpResponse()
	# 以字典的形式，自定义为response对象扩展属性
	response['Age'] = 25
	response['Name'] = 'youyou'
	# 删除属性
	del response['Name']

	# 将响应头对象当作文件读写对象(file-like-object)返回，注意一定要用return语句返回
	response.write("<p>Here's the text of the Web page.</p>")
	response.write("<p>Here's another paragraph.</p>")
	return response

def test2(request):
	data = {
		"name":"test2"
	}
	return render(request,'polls/test2.html',context=data,content_type='text/plain')

def latest(request):
    return HttpResponse("You're looking at latest.html")

def detail(request,question_id):
	# 重写捕获异常返回的信息
	# try:
	# 	question = Question.objects.get(pk=question_id)
	# except Question.DoesNotExist:
	# 	raise Http404("Question does not exist")
	# # return HttpResponse("You're looking at question %s." % question_id)

	# 可以使用get_object_or_404或者get_list_or_404替代上面的异常捕获
	# 1:
	# queryset = Question.objects.filter(question_text__startswith='W') #返回一个Queryset实例，并不是List实例
	# print queryset,type(queryset)
	# question = get_object_or_404(queryset,pk=question_id)
	# 2:
	question = get_object_or_404(Question,pk=question_id)
	# 3:
	# question = get_object_or_404(Question,question_text__startswith='W',pk=question_id)
	# 4:
	# question = get_list_or_404(Question,pk=question_id)#get_list_or_404()返回的是一个List实例

	return render(request,'polls/details.html',context={"question":question})

class DetailView(generic.DetailView):
	# 需要使用model属性指定视图类作用于哪个模型
	model = Question
	template_name = 'polls/details.html'

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())





def results(request,question_id):
	# question = Question.objects.get(pk=question_id)
	# response = "You're looking at the results of question %s(%s)."
	# return HttpResponse(response % (question_id,question.question_text))

	question = get_object_or_404(Question,pk=question_id)
	return render(request,'polls/results.html',{"question":question})

# 访问某个具体数据时，它是通过pk字段进行访问查询的，所以urls.py中的question_id需要改成pk
class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):
	question = get_object_or_404(Question,pk=question_id)
	try:
		print request.POST['choice']
		# 查询指定id的choice与当前question对象相关的choice对象
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError,Choice.DoesNotExist):#
		return render(request,'polls/details.html',{
				'question':question,
				'error_message':"You didn't select a choice!",
			})
	else:
		# 更新choice对象并保存到数据库中
		selected_choice.votes +=1
		selected_choice.save()
		# 页面重定向到results页面，使用reverse函数将url和参数结合起来返回一个string
		# return HttpResponseRedirect(reverse('polls:results',args=(question_id,)))
		# 或者：
		return HttpResponseRedirect(reverse('polls:results',kwargs={'pk':question_id},current_app='polls'))
    	# return HttpResponse("You're voting on question %s." % question_id)

Django/day02/mysite/polls/templates/polls/details.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>{{question.question_text}}</h1>
	{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
	<form action="{% url 'polls:vote' question.id %}" method = "post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
			<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
		{% endfor %}
		<input type="submit" name="Vote">
	</form>
</body>
</html>

Django/day02/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>主页</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
</head>
<body>
	{% if latest_question_list %}
		<ul>
			{% for question in latest_question_list %}
				<li>
					<!-- <a href="/polls/{{question.id}}/">{{question.question_text}}--{{question.pub_date}}</a> -->
					detail:
					<a href="{% url 'polls:detail' question.id %}">{{question.question_text}}--{{question.pub_date}}</a><br>
					detail2:
					<a href="{% url 'polls:detail2' question.id %}">{{question.question_text}}--{{question.pub_date}}</a>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No polls are available.</p>
	{% endif %}
	<h1>{{message}}--{{now|date}}</h1>
	<div>
		<h2>使用拼接的url路径</h2>
		<image src="/static/polls/images/test.jpg"><br>
		<h2>使用static指令拼接路径</h2>
		<image src="{% static 'polls/images/test.jpg' %}">
	</div>
	<script type="text/javascript" src="{% static 'polls/js/style.js' %}"></script>
</body>
</html>

Django/day02/mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>{{question.question_text}}</h1>
	<ul>
		{% for choice in question.choice_set.all %}
			<li>{{choice.choice_text}}--{{choice.votes}}vote{{choice.votes|pluralize}}</li>
		{% endfor %}
	</ul>
	<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

Django/day02/mysite/polls/templates/polls/test2.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	you looking at {{name}}
</body>
</html>

Django/day02/mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>公共模板</title>
</head>
<body>
	base.html
</body>
</html>